package com.tillzo.pos.ui.store.options.statement

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.tillzo.pos.data.local.entity.CustomerEntity
import com.tillzo.pos.data.local.entity.KhataEventEntity
import com.tillzo.pos.domain.repository.StoreRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject

@HiltViewModel
class StatementViewModel @Inject constructor(
    private val storeRepository: StoreRepository
) : ViewModel() {

    private val _customer = MutableStateFlow<CustomerEntity?>(null)
    val customer = _customer.asStateFlow()

    private val _events = MutableStateFlow<List<KhataEventEntity>>(emptyList())
    val events = _events.asStateFlow()

    private val _baqaya = MutableStateFlow(0.0)
    val baqaya = _baqaya.asStateFlow()

    fun loadData(customerId: String) {
        viewModelScope.launch {
            _customer.value = storeRepository.getCustomerById(customerId)
        }
        viewModelScope.launch {
            storeRepository.getKhataEventsForCustomer(customerId).collect {
                _events.value = it
            }
        }
        viewModelScope.launch {
            storeRepository.getCustomerBaqaya(customerId).collect {
                _baqaya.value = it
            }
        }
    }

    fun generateWhatsAppMessage(): String {
        val cust = _customer.value ?: return ""
        val formatter = SimpleDateFormat("dd MMM, hh:mm a", Locale.getDefault())
        
        val builder = java.lang.StringBuilder()
        builder.append("*Account Statement - Tillzo POS*\n")
        builder.append("Customer: ${cust.name}\n")
        builder.append("Current Balance (Baqaya): *Rs ${String.format("%.2f", _baqaya.value)}*\n\n")
        builder.append("Recent Transactions:\n")

        // Take last 10 events for brevity in WhatsApp
        val recentEvents = _events.value.take(10)
        for (event in recentEvents) {
            val date = formatter.format(Date(event.created_at))
            val typeStr = if (event.event_type == "UDHAAR") "Udhaar (-)" else "Jama (+)"
            val amt = Math.abs(event.amount)
            builder.append("- $date: $typeStr Rs $amt")
            if (!event.note.isNullOrBlank()) {
                builder.append(" (${event.note})")
            }
            builder.append("\n")
        }
        
        builder.append("\n_System Generated by Tillzo POS_")
        return builder.toString()
    }
}
